#pipeline CI
name: Backend CI
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      REPOSITORY: ${{ secrets.REPOSITORY }}


    steps:
      - uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # Autenticación GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Debug variables
        run: |
         echo "REGION=${REGION}"
         echo "PROJECT_ID=${PROJECT_ID}"
         echo "IMAGE_TAG=${IMAGE_TAG}"


      # Build imágenes api-gateway, academic-service, users-service
      - name: Build api-gateway
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/api-gateway:${IMAGE_TAG} ./api-gateway

      - name: Build users-service
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/users-service:${IMAGE_TAG} ./users-service

      - name: Build academic-service
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/academic-service:${IMAGE_TAG} ./academic-service

      # Security Scan
      - name: Scan api-gateway
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/api-gateway:${IMAGE_TAG}

      # Push imágenes
      - name: Push images
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/api-gateway:${IMAGE_TAG}
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/users-service:${IMAGE_TAG}
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}/academic-service:${IMAGE_TAG}